apiVersion: apps/v1
kind: deployment
metadata:
  name: bitlybot-api
  labels:
    app.kubernetes.io/name: bitlybot-api
    app.kubernetes.io/instance: bitlybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitlybot-api
      app.kubernetes.io/instance: bitlybot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitlybot-api
        app.kubernetes.io/instance: bitlybot
    spec:
      containers:
        - name: bitlybot
          image: "jharshman/bitlybot"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 1G
            requests:
              cpu: 50m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bitlybot-api
  labels:
    app.kubernetes.io/name: bitlybot-api
    app.kubernetes.io/instance: bitlybot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bitlybot-api
    app.kubernetes.io/instance: bitlybot
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bitlybot-api
  labels:
    app.kubernetes.io/name: bitlybot-api
    app.kubernetes.io/instance: bitlybot
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bitlybot-api
spec:
  backend:
    serviceName: bitlybot-api
    servicePort: 8080

